services:
  - type: web
    name: recipe-builder
    runtime: node
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: DATABASE_URL
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: ADMIN_EMAIL
        value: admin@recipebuilder.com
      - key: ADMIN_PASSWORD
        value: admin123
